---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp -r * $DEPLOYPATH
 setup:
  - command: "composer install --no-dev"
    cwd: ""
  - command: "php artisan key:generate"
    cwd: ""
  - command: "php artisan migrate"
    cwd: ""
deploy:
  - command: "git pull origin master"
    cwd: ""
  - command: "composer install --no-dev"
    cwd: ""
  - command: "php artisan migrate"
    cwd: ""
